### ISSUE TITLE
NPU firmware search path not persistent across reboots

### ISSUE THREAD

**Issue by hector-cao** [canonical/intel-npu-driver-snap#2]
Currently, at npu driver snap installation, the snap will invoke a hook to write a customized path to `/sys/module/firmware_class/parameters/path` to give the NPU firmware files path to the kernel.

Apparently, when we reboot, this path will not be set again and the kernel will not be able to find the wanted NPU firmware

**Comment by frenchwr** [comment]
Thanks @hector-cao . This is not something I had considered.

Just to be clear, the path is technically written when the `intel-npu-fw` plug is connected with:

```
sudo snap connect intel-npu-driver:intel-npu-fw
```

I'm not sure how connections behave on reboots. Do manual connections persist? Do autoconnections re-connect, thus re-triggering any hooks that are configured on the snap? I searched online briefly but didn't find any quick answers, so we'll need to test.

A workaround for now would be to reconnect the interface following a reboot. Long term, if we implement a new NPU interface for snapd we could add permissions to allow writes to a permanent path on the host and install the firmware there rather than using `/sys/module/firmware_class/parameters/path`.

**Comment by hector-cao** [comment]
@frenchwr for now, we do not have auto-connection, so if you require following actions as prerequisites upon npu driver usage after reboot or fresh install:
- sudo snap connect intel-npu-driver:intel-npu-fw
- reload intel vpu driver

it should be better.

However, i think there is anyway room for improvement, i think we should see the npu-fw as one-off operation that is tight to the kernel driver reload. These two operations must be tight together as one single logical operation : `reload vpu driver with new NPU firmware path`. One this operation is done, we forget about the firmware path configuration and do not have any assumptions about that

**Comment by hector-cao** [comment]
One design would be, upon a connection of consumer snap, npu snaps tries to reload the kernel driver with the customized firmware path (if necessary - the content of path parameter is different than the one npu driver wants)

**Comment by frenchwr** [comment]
@hector-cao I like your idea. I agree that ideally the driver will be reloaded by the snap so the new firmware is loaded transparently for the user. Long term we should also automate updating the permissions on the device node as they are reverted each time the drivers are reloaded. I think all of this is possible.

**Comment by hector-cao** [comment]
One thing we could be aware of and that could help us to have an other design is that the intel npu module accepts a parameter (similar to firmware_class path) to know where to look for the firmwares, we can make this parameter persistent by modifying kernel boot command line (by grub), so upon reboot, the driver is good and we usually no longer have to reload the driver at runtime
